version: "3.9"

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - global_network
    depends_on:
      - server
    env_file:
      - .env

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_URL=${CLIENT_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - N8N_CONTENT_GENERATION_WEBHOOK_URL=${N8N_CONTENT_GENERATION_WEBHOOK_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - META_APP_SECRET=${META_APP_SECRET}
    networks:
      - global_network
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - global_network

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - GENERIC_WEBHOOK_URL=${GENERIC_WEBHOOK_URL}
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - global_network
    env_file:
      - .env

networks:
  global_network:
    driver: bridge

volumes:
  mongo_data:
