version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
      - n8n
    networks:
      - global_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt

    restart: unless-stopped

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://107.20.220.167}
      - NEXTAUTH_SECRET=844efe23b9b81ad485b25d11b1f5548b2e8862010576da1c53c41df2b01cc546
      - INTERNAL_API_URL=http://server:3001
      - NEXT_PUBLIC_N8N_WEBHOOK_URL=${NEXT_PUBLIC_N8N_WEBHOOK_URL:-http://localhost:5678/webhook/content-generation}
      - NEXT_PUBLIC_N8N_LEGAL_ASSISTANT_WEBHOOK_URL=${NEXT_PUBLIC_N8N_LEGAL_ASSISTANT_WEBHOOK_URL:-http://localhost:5678/webhook/legal-assistant}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
    networks:
      - global_network
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/global-agent-ai
      - CLIENT_URL=${CLIENT_URL}
      - FRONTEND_URL=${CLIENT_URL}
      - BACKEND_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - N8N_CONTENT_GENERATION_WEBHOOK_URL=http://n8n:5678/webhook-test/content-generation
      - N8N_LEGAL_ASSISTANT_WEBHOOK_URL=http://n8n:5678/webhook-test/legal-assistant
      # OAuth Credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      # Variables de Twilio
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      # Variable de Meta App Secret
      - META_APP_SECRET=${META_APP_SECRET}
      - META_APP_ID=${META_APP_ID}
      # Variables de Mercado Pago
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - MERCADOPAGO_PUBLIC_KEY=${MERCADOPAGO_PUBLIC_KEY}
      - MERCADOPAGO_WEBHOOK_SECRET=${MERCADOPAGO_WEBHOOK_SECRET}
      # JWT Secret
      - JWT_SECRET=${JWT_SECRET}
      
    depends_on:
      - mongo
    networks:
      - global_network

  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - global_network

  n8n:
    image: n8nio/n8n
    restart: always
    expose:
      - "5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_CORS_ORIGIN=*
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - WEBHOOK_URL=http://n8n:5678 
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - GENERIC_WEBHOOK_URL=http://n8n:5678 
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - global_network

networks:
  global_network:
    driver: bridge

volumes:
  mongo_data:
